### ISSUE TITLE
rust_icu requires non-stable toolchain

### ISSUE THREAD

**Issue by filmil** [google/rust_icu#10]
README.md should note this, and explain how to set up the toolchain.

```
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> rust_icu_sys/src/lib.rs:1:1
```

**Comment by kpozin** [comment]
Alternatively, https://doc.rust-lang.org/unstable-book/language-features/link-args.html suggests
> It is highly recommended to not use this attribute, and rather use the more formal `#[link(...)]` attribute on `extern` blocks instead.

**Comment by filmil** [comment]
Good to know.  I think I tried but failed to do that once upon a time, but I may have been holding it wrong.

**Comment by filmil** [comment]
https://github.com/filmil/rust_icu/commit/aadd3b14bbf2c153ac6ccbe29cdb0ce16e800b61 adds a bullet point to the prerequisites.
