### ISSUE TITLE
Build failures without features in rust_icu_ucol & rust_icu_umsg

### ISSUE THREAD

**Issue by betamos** [google/rust_icu#111]
Repro:

```bash
cd rust_icu_ucol
cargo build --no-std-features
```

```bash
cd rust_icu_umsg
cargo build --no-std-features
```

Both libs refer to non-existing items from the sys crate.

Context: this affected Fuchsia builds using the "renaming" feature only (no default features).

**Comment by filmil** [comment]
I believe this only fails with ICU 64, as all other versions have been updated. 

Thanks for reporting!

**Comment by filmil** [comment]
This code note is relevant: https://github.com/google/rust_icu/commit/dc138503d570e4d471a1d2896da7d1de17044f37#diff-fe8421955fd596131bb6f1b78984b2fbR23

**Comment by filmil** [comment]
@betamos See https://github.com/google/rust_icu/pull/112.  I believe this backfills all missing feature tests to cover Fuchsia's current use of `rust_icu`.

**Comment by filmil** [comment]
https://github.com/google/rust_icu/pull/112 fixes this issue.  We're now testing all ICU versions with renaming feature on.
