### ISSUE TITLE
Release a new version of rust_icu

### ISSUE THREAD

**Issue by filmil** [google/rust_icu#124]
Two significant changes:

- Feature testing stabilization
- Feature build fix for `rust_icu_uloc`

I propose uprevving the minor, i.e. releasing 0.3.0.

**Comment by filmil** [comment]
@betamos @kpozin WDYT?

**Comment by kpozin** [comment]
SGTM

**Comment by filmil** [comment]
This has been fixed with the release of rust_icu 0.3.0.
