### ISSUE TITLE
No Transliterate? (utrans.h)

### ISSUE THREAD

**Issue by tsukit** [google/rust_icu#157]
Hi there. I don't see the mapping to `utrans.h` in C API, or anything that's for transliterate (http://userguide.icu-project.org/transforms/general). But I might have missed it. If there's current support for it, could you please point me to it?

**Comment by filmil** [comment]
Hi tsukit@.  You haven't missed anything, rust_icu doesn't yet have complete coverage.  If you want to contribute `utrans.h`, we'd be very glad to accept the contribution.

**Comment by filmil** [comment]
This is now implemented.  Thanks to @bdragon .
