### ISSUE TITLE
normalize_ustring hard-codes the output capacity to 200

### ISSUE THREAD

**Issue by hsivonen** [google/rust_icu#244]
Normalization fails if the output of the operation is longer than 200 UTF-16 code units, because the [output capacity is hard-coded](https://github.com/google/rust_icu/blob/e56a1a3452365f37964053ad16e5b67433cc40ae/rust_icu_unorm2/src/lib.rs#L96). Expected the code to deal with variable-length output.

**Comment by filmil** [comment]
What error are you getting, and could you provide a repro test?

The output capacity you linked to is not hard coded; rather it's the capacity of the initial buffer - the idea is if the initial buffer is not overflowed that we don't need to redo the call. But if it overflows, we repeat the call using the needed buffer size that was discovered during preflight.

See here: https://docs.rs/rust_icu_ustring/latest/src/rust_icu_ustring/lib.rs.html#86

**Comment by hsivonen** [comment]
Here's the repro (67 Hangul syllables that decompose to 3 jamo each, i.e. 201 jamo):

```rust
use rust_icu_ustring::UChar;
use rust_icu_unorm2::UNormalizer;

fn main() {
    let s = "탐탐퀀탐탐탐탐탐탐탐탐탐탐탐탐탐탐탐탐탐탐탐탐탐탐탐탐탐탐탐탐탐탐탐탐탐탐탐탐탐탐탐탐탐탐탐탐탐탐탐탐탐탐탐탐탐탐탐탐탐탐탐탐탐탐탐탐";
    let u = UChar::try_from(s).unwrap();
    let normalizer = UNormalizer::new_nfd().unwrap();
    normalizer.normalize_ustring(&u).unwrap();
}
```

The failure with `rust_icu` 2.0.2 and system ICU from Ubuntu 20.04 is (but I first saw this with `rust_icu` trunk and ICU4C nearly-current trunk):
`
thread 'main' panicked at 'assertion failed: common::Error::is_ok(status)', /home/hsivonen/.cargo/registry/src/github.com-1ecc6299db9ec823/rust_icu_unorm2-2.0.2/src/lib.rs:97:9`

**Comment by filmil** [comment]
> Here's the repro (67 Hangul syllables that decompose to 3 jamo each, i.e. 201 jamo):

Thank you I have a fix.

**Comment by filmil** [comment]
@hsivonen you can now try 2.0.3 and see if it works for you. 

Thank you for your patience.

**Comment by hsivonen** [comment]
Thanks. My test case now passes.
