### ISSUE TITLE
Support UCPTrie and UMutableCPTrie

### ISSUE THREAD

**Issue by sffc** [google/rust_icu#247]
Currently ICU4X supports UCPTrie but not UMutableCPTrie, which is required to build UCPTrie. It would be nice if rust_icu could make the ICU4C implementation of this available to Rust clients until ICU4X implements it in Rust.

https://unicode-org.github.io/icu-docs/apidoc/dev/icu4c/umutablecptrie_8h_source.html

ICU4X issue: https://github.com/unicode-org/icu4x/issues/1837

**Comment by filmil** [comment]
What user is missing this feature today?

**Comment by sffc** [comment]
It would be nice to leverage in ICU build tools.

**Comment by filmil** [comment]
Hm, in that case would you or someone from the more regular set of ICU4X contributors care to add the wrapper for the functionality you need?

**Comment by sffc** [comment]
I ended up writing a small C++ command-line tool for this for the short term.

**Comment by filmil** [comment]
sffc@ no longer needs this, closing.
