### ISSUE TITLE
Release and publish ICU version 0.1.1

### ISSUE THREAD

**Issue by filmil** [google/rust_icu#60]
Quite a few improvements here, including language tags and matching (@kpozin) and build process cleanup (@benbrittain).

**Comment by filmil** [comment]
Ah, yes, also -- message formatting.

**Comment by benbrittain** [comment]
Awesome! Thanks for the timely release!

**Comment by filmil** [comment]
All 0.1.1 crates are now available on https://crates.io.

See for example: https://crates.io/crates/rust_icu_umsg (this is new!)
