### ISSUE TITLE
Add time-zone related methods to `UCalendar`

### ISSUE THREAD

**Issue by kpozin** [google/rust_icu#73]
There's been a request to expose functionality to get time zone offsets for a given time zone. The direct method, [`icu::TimeZone::getOffset()`](https://unicode-org.github.io/icu-docs/apidoc/released/icu4c/classicu_1_1TimeZone.html#afcbc1c48bf0b453b0123c4cb75d20e96), does not seem to have an equivalent in C, but a workaround can be cobbled together out of a few methods in `ucal.h`.

**Comment by filmil** [comment]
I remember attempting to do this before, and giving up.  Sadly I forget the reason, so I can't caution you about anything specific, but wanted to let you know to be generally aware of potential sharp corners.

(Could have been an unrelated issue too, sadly lost in the mist of forgetfulness... )
